/* Generated By:JavaCC: Do not edit this line. EasycodeConstants.java */
package github.com.hicaosen;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EasycodeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PACKAGE = 5;
  /** RegularExpression Id. */
  int DEF = 6;
  /** RegularExpression Id. */
  int MODEL = 7;
  /** RegularExpression Id. */
  int DAO = 8;
  /** RegularExpression Id. */
  int SERVICE = 9;
  /** RegularExpression Id. */
  int EXPORT = 10;
  /** RegularExpression Id. */
  int IDENTIFIER = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int LBRACE = 13;
  /** RegularExpression Id. */
  int RBRACE = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"package\"",
    "\"def\"",
    "\"model\"",
    "\"dao\"",
    "\"service\"",
    "\"export\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
  };

}
